[package]
name = "kisu"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = "0.16.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"

[workspace]
members = ["cli"]

[dev-dependencies]
indoc = "2.0.7"
