[package]
name = "kisu-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
miette = { version = "7.6.0", features = ["fancy"] }
kisu = { path = "../", default-features = false }
indicatif = "0.18.3"
